config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items, path: 'photos'
  resources :lineitems
  resources :orders, path: 'commandes'
  resources :carts, path: 'panier'
  resources :charges, path: 'paiement'

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :photos, path_names: { new: 'make', edit: 'change' }
  
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true 
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :lineitems


    def add_item(item)
        
        product = lineitems.find_by(item_id: item)
        
        if product
            product.quantity +=1 
        else 
            product = lineitems.new(item: item)
        end
        product
    end

    def total 
        lineitems.to_a.sum(&:total)
    end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  
  has_many :lineitems
  has_many :order_forms
  has_many :order, through: :order_forms
  

end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
    belongs_to :cart 
    belongs_to :item
    

     def total
     total = quantity * item.price
     end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items
    belongs_to :user


    has_many :order_forms
    has_many :items, through: :order_forms


    after_create :order_save
    after_create :order_send


    def order_save
        puts " ==== INFORMATION MAIL METHOD STARTING === "
        OrderMailer.new_order_email(@order).deliver_now
    end

    def order_send
        OrderMailer.order_email(self).deliver_now
      end 

end

app/models/order_form.rb
class OrderForm < ApplicationRecord
 
  belongs_to :item
  belongs_to :order

    
end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

  validates_presence_of :first_name, :last_name

  has_one :cart

  has_many :items, through: :carts
  has_many :orders


  has_one_attached :avatar

  after_create :welcome_send

  def welcome_send
    puts " ==== WELCOME SEND METHOD STARTING === "
    UserMailer.welcome_email(self).deliver_now
  end


  def user_cart
    Cart.create(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_params, if: :devise_controller?

  private

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
before_action :set_cart, only: [:show]

    def show 
        @cart = Cart.find(params[:id])
        if current_user.id != Cart.find(params[:id]).user_id
          redirect_to root_path
        end     
    end

    def destroy
        @carts = Cart.find(params[:id])
        @carts.destroy
      end

private

  def set_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/charges_controller.rb
require 'pry'
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @cart = current_user.cart
    @amount = (@cart.total * 100).to_i

  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
   
    if customer.save && charge.save
    @order = Order.create(stripe_customer_id: customer.id, user_id: current_user.id)

     @cart.lineitems.destroy_all
      redirect_to root_path
    else
     render 'new'
  end

    @order_items = @cart.lineitems.each do |item|
    @order_form =OrderForm.create(order_id: @order.id, item_id: item.id)
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

  def set_cart

    @cart =Cart.find_or_create_by(user_id: current_user.id)

  end  

end 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/lineitems_controller.rb
require 'pry'
class LineitemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def index
    
  end

  def create
  
    item = Item.find(params[:item_id])
    @lineitem = @cart.add_item(item)
   
    
    respond_to do |format|
      if @lineitem.save 
        format.html {redirect_to @lineitem.cart, notice: 'Line item was successfully created.'}
      else 
        format.html {render :new}
      end
    end
  end

  def show
  end

  def destroy
    @lineitem = Lineitem.find(params[:id])
    @lineitem.destroy
    redirect_to @lineitem.cart
  end

  private 

  def set_lineitem
   @lineitem = Lineitem.find(params[:id])
  end

  def lineitem_params
    params.require(:lineitem).permit(:cart_id, :item_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        @order = Order.new(order_params)
        @current_cart.line_items.each do |item|
          @order.line_items << item
          item.cart_id = nil
        end
        @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        redirect_to root_path
      end
      
      private
        def order_params
          params.require(:order).permit(:name, :email, :address, :pay_method)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
    
  end

  def secret
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create

    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    email: params[:mail])
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'users', :action => 'index'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_card.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <img class="card-img-top"><%= items.image_url %><alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= items.title %></h5>
      <button type="button" class="btn btn-outline-primary"><%= link_to "Voir détails", item_path %></button>
      <p class="card-text"><small class="text-muted"><%= items.price %>€</small></p>
    </div>
  </div>
</div>

app/views/items/_catpage.html.erb
  
  <body class= "catpage" >
    <header>
    </header>  

      <div class= "colorcatpage container col-10">
        <div class="row mb-3">
          <div class="col-md-8 themed-grid-col">
            <div class="block-image">
               <img class="img-thumbnail" sizes="720px";><%= image_tag  @item.image_url%>
          </div>
          </div>
          
          <div class="col-6 col-md-4 mb-4 themed-grid-col">
              <p>Information du catoone trop choupitoune</p>
              <h5 class="card-title"><%= @item.title %></h5>
              <p class="card-text"><%= @item.description%></p>
              <h5 class="card-price"><%= @item.price%>€</h5>
              <% if user_signed_in? %>
              <button type="button" class="btn btn-outline-primary"><%= link_to "Ajouter au panier", lineitems_path(item_id: @item.id), method: 'POST' %></button>
              <% else %>
              <%end%>
          </div>
        </div>

        <div class="row mb-3">
          <div class="col-lg-10 themed-grid-col">
          
            <ul class="nav nav-pills nav-fill">
              <li class="nav-item">
                <a  href="#"> <i class="fas fa-share-square fa-2x" ></i></a>
              </li>
              <li class="nav-item">
                <a  href="#">  <i class="fab fa-gratipay fa-2x"></i></a>
              </li>
              <li class="nav-item">
              </li>
            </ul>
          </div>
        </div>

        <div class="row mb-3">
          <div class="col-md-8 themed-grid-col">
          </div>
          <div class="col-6 col-md-4 themed-grid-col">
            <h5 class="card-title">PS:</h5>
            <p class="card-text">Venez avec une musolière lorsque vous viendrez le récupérer</p>
          </div>
        </div>
        
      </div>
    


  </body>

    

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class = "bannertitle homescreen">
      <div class="jumbotron text-center">
        <h1 class="display-3 font-size-48--md-down">Catoune website</h1>
        <p class="lead font-weight-bold">Le site qui vous changera la vision de la litière.</p>
        <p class ="lead text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </p>
      </div>
    </div>


<div class="row ">
  <% @items.each do |items|%>
    <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <img class="card-img-top"><%= image_tag items.image_url %><alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= items.title %></h5>
        <button type="button" class="btn btn-outline-primary"><%= link_to "Voir détails", item_path(items.id) %></button>


        <% if user_signed_in? %>

        <button type="button" class="btn btn-outline-primary"><%= link_to "Ajouter au panier", lineitems_path(item_id: items.id), method: 'POST' %></button>

        <% else %>
        
        <%end%>
        <h4 class="card-text"><small class="text-muted"><%= items.price %>€</small></h4>
      </div>
    </div>
  </div>
  
  <% end %>
</div>
   

   
   

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<main class="container mb-5 mt-5">




<%= render 'catpage' %>

<main class="container mb-5 mt-5">

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/orders/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Line Items: </p>
  <ul>
    <% order.lineitems.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
<% end

app/views/users/show.html.erb
<h1>Page Profil</h1>

<p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@user.id%></p>
<h3>Avatar actuel</h3>
<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>

<h3>Changer d'avatar ?</h3>

<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>