config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items, path: 'photos'
  resources :lineitems
  resources :orders, path: 'commandes'
  resources :carts, path: 'panier'
  resources :charges, path: 'paiement'

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :photos, path_names: { new: 'make', edit: 'change' }
  
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true 
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :lineitems


    def add_item(item)
        
        product = lineitems.find_by(item_id: item)
        
        if product
            product.quantity +=1 
        else 
            product = lineitems.new(item: item)
        end
        product
    end

    def total 
        lineitems.to_a.sum(&:total)
    end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  
  has_many :lineitems
  has_many :order_forms
  has_many :order, through: :order_forms
  

end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
    belongs_to :cart 
    belongs_to :item
    

     def total
     total = quantity * item.price
     end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items
    belongs_to :user


    has_many :order_forms
    has_many :items, through: :order_forms


    after_create :order_save
    after_create :order_send


    def order_save
        puts " ==== INFORMATION MAIL METHOD STARTING === "
        OrderMailer.new_order_email(@order).deliver_now
    end

    def order_send
        OrderMailer.order_email(self).deliver_now
      end 

end

app/models/order_form.rb
class OrderForm < ApplicationRecord
 
  belongs_to :item
  belongs_to :order

    
end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

  validates_presence_of :first_name, :last_name

  has_one :cart

  has_many :items, through: :carts
  has_many :orders


  has_one_attached :avatar

  after_create :welcome_send

  def welcome_send
    puts " ==== WELCOME SEND METHOD STARTING === "
    UserMailer.welcome_email(self).deliver_now
  end


  def user_cart
    Cart.create(user_id: self.id)
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
before_action :set_cart, only: [:show]

    def show 
        @cart = Cart.find(params[:id])
        if current_user.id != Cart.find(params[:id]).user_id
          redirect_to root_path
        end     
    end

    def destroy
        @carts = Cart.find(params[:id])
        @carts.destroy
      end

private

  def set_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/charges_controller.rb
require 'pry'
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @cart = current_user.cart
    @amount = (@cart.total * 100).to_i

  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
   
    if customer.save && charge.save
    @order = Order.create(stripe_customer_id: customer.id, user_id: current_user.id)

     @cart.lineitems.destroy_all
      redirect_to root_path
    else
     render 'new'
  end

    @order_items = @cart.lineitems.each do |item|
    @order_form =OrderForm.create(order_id: @order.id, item_id: item.id)
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/lineitems_controller.rb
require 'pry'
class LineitemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def index
    
  end

  def create
  
    item = Item.find(params[:item_id])
    @lineitem = @cart.add_item(item)
   
    
    respond_to do |format|
      if @lineitem.save 
        format.html {redirect_to @lineitem.cart, notice: 'Line item was successfully created.'}
      else 
        format.html {render :new}
      end
    end
  end

  def show
  end

  def destroy
    @lineitem = Lineitem.find(params[:id])
    @lineitem.destroy
    redirect_to @lineitem.cart
  end

  private 

  def set_lineitem
   @lineitem = Lineitem.find(params[:id])
  end

  def lineitem_params
    params.require(:lineitem).permit(:cart_id, :item_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        @order = Order.new(order_params)
        @current_cart.line_items.each do |item|
          @order.line_items << item
          item.cart_id = nil
        end
        @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        redirect_to root_path
      end
      
      private
        def order_params
          params.require(:order).permit(:name, :email, :address, :pay_method)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create

    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    email: params[:mail])
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'users', :action => 'index'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |msg| %>
  <%= msg %>
<% end %>
OR
<% if alert.present? %> # or :notice
 <%= alert %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="datefooter"> 
          <p>2020</p>
          </div>
          <div class="col-6 col-md">
            <h5> À propos </h5>
            <p>Site réalisé par Louison Boisselier, Emma Le Goof, Emilie Aussage et Lola Leandri. </p>
          </div>
      </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Le Roi des Chats", root_path, class:"navbar-brand" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
         <%= link_to "Accueil", items_path, class:"nav-link" %> 
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item active">
      <%= link_to "Panier", cart_path(current_user.id), class:"nav-link" %> <i class="fas fa-shopping-cart"></i> <b>
      <span class="sr-only">(current)</span>
     </a>
    </li>
    <%else%>

    <%end%>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
        <div class="dropdown-menu">
        <%if user_signed_in?%>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          <%= link_to "Profil", edit_user_registration_path, class:"dropdown-item" %>
        <%else%>
          <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %>
          <%= link_to "Log in", new_user_session_path, class:"dropdown-item" %>
        <%end%> 
        </div>
      </li>
    </ul>

  </div>
</nav>


    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to "Accueil", items_path, class:"nav-link" %> 
            <span class="sr-only">(current)</span>
        </li>
        <li class="nav-item active">
          <%= link_to "Connexion", new_user_session_path, class:"nav-link" %> 
        </li>
        <li class="nav-item active">
         <%= link_to "Inscription", new_user_registration_path, class:"nav-link" %> 
        </li>
        <li class="nav-item active">
         <%= link_to "Log out",  destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item active">
        <%= link_to "Mon Panier", class:"nav-link" %>
        </li>
      </ul>
      <form class="btn-group-inline my-2 my-lg-0" data-children-count="1">
        <ul>
          <%if user_signed_in?%>
            <div class="btn-group">
              <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My profile
              </button>
              <div class="dropdown-menu">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
              </div>
            </div>
          <%else%>
            <div class="btn-group">
              <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Log in / Inscription
              </button>
              <div class="dropdown-menu">
                <%= link_to "Log in", new_user_session_path, class:"dropdown-item" %> 
                <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %> 
              </div>
            </div>
          <%end%>
        </ul>
      </form>
    </div>
  </nav>

app/views/layouts/_showproduct.html.erb
<div class="modal fade" id="productView" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div class="row align-items-stretch">
          <div class="col-lg-6 p-lg-0"><a class="product-view d-block h-100 bg-cover bg-center" style="background: url(img/product-5.jpg)" href="img/product-5.jpg" data-lightbox="productview" title="Red digital smartwatch"></a><a class="d-none" href="img/product-5-alt-1.jpg" title="Red digital smartwatch" data-lightbox="productview"></a><a class="d-none" href="img/product-5-alt-2.jpg" title="Red digital smartwatch" data-lightbox="productview"></a></div>
          <div class="col-lg-6">
            <button class="close p-4" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <div class="p-5 my-md-4">
              <ul class="list-inline mb-2">
                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
              </ul>
              <h2 class="h4">Red digital smartwatch</h2>
              <p class="text-muted">$250</p>
              <p class="text-small mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.</p>
              <div class="row align-items-stretch mb-4">
                <div class="col-sm-7 pr-sm-0">
                  <div class="border d-flex align-items-center justify-content-between py-1 px-3"><span class="small text-uppercase text-gray mr-4 no-select">Quantity</span>
                    <div class="quantity">
                      <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                      <input class="form-control border-0 shadow-0 p-0" type="text" value="1">
                      <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs border-0" id="myTab" role="tablist">
  <li class="nav-item"><a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a></li>
  <li class="nav-item"><a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">Reviews</a></li>
</ul>
<div class="tab-content mb-5" id="myTabContent">
  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
    <div class="p-4 p-lg-5 bg-white">
      <h6 class="text-uppercase">Product description </h6>
      <p class="text-muted text-small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
  <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
    <div class="p-4 p-lg-5 bg-white">
      <div class="row">
        <div class="col-lg-8">
          <div class="media mb-3"><img class="rounded-circle" src="img/customer-1.png" alt="" width="50">
            <div class="media-body ml-3">
              <h6 class="mb-0 text-uppercase">Jason Doe</h6>
              <p class="small text-muted mb-0 text-uppercase">20 May 2020</p>
              <ul class="list-inline mb-1 text-xs">
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star-half-alt text-warning"></i></li>
              </ul>
              <p class="text-small mb-0 text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
          <div class="media"><img class="rounded-circle" src="img/customer-2.png" alt="" width="50">
            <div class="media-body ml-3">
              <h6 class="mb-0 text-uppercase">Jason Doe</h6>
              <p class="small text-muted mb-0 text-uppercase">20 May 2020</p>
              <ul class="list-inline mb-1 text-xs">
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                <li class="list-inline-item m-0"><i class="fas fa-star-half-alt text-warning"></i></li>
              </ul>
              <p class="text-small mb-0 text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Catoune | Website</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <!-- Lightbox-->
    <link rel="stylesheet" href="vendor/lightbox2/css/lightbox.min.css">
    <!-- Range slider-->
    <link rel="stylesheet" href="vendor/nouislider/nouislider.min.css">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="vendor/bootstrap-select/css/bootstrap-select.min.css">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="vendor/owl.carousel2/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="vendor/owl.carousel2/assets/owl.theme.default.css">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <link rel="stylesheet" href="app/asset/stylesheets/stripe.scss">
    <link href="https://www.flaticon.com/svg/static/icons/svg/616/616596.svg" rel="shortcut icon">
        

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/17892e5f3b.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
   

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/order_forms/index.html.erb
im the one you looking for : )

app/views/shared/_banner.html.erb
<div class="bannertitle headerpages">
  <div class="jumbotron headerpagesbackground">
    <h1 class="display-3 font-size-48--md-down mb-4">
      <strong class="u-text-animation u-text-animation--typing">Cat un jour catoujours !</strong>
    </h1>
    <hr class="my-4">
    <p class="lead font-weight-bold">Un jour je serais un tigre.</p>
  </div>
</div>